import{FormEvent,useEffect,useRef,useState}from'react'
import{createConversation,getConversation,listConversations,streamMessage}from'./api'
import type{Conversation,Message}from'./types'
const primary=[['⌁','智能工作台'],['▣','常用应用']],build=[['◇','应用开发'],['▦','应用模板']],resources=[['▤','知识库'],['◉','模型'],['♧','Skills'],['↗','连接器与工具'],['▱','提示词']],manage=[['⌁','数据报表'],['⚙','权限管理']]
function NavGroup({label,items}:{label:string;items:string[][]}){return <><p>{label}</p>{items.map(([icon,name])=><button className={name==='智能工作台'?'active':''} key={name}><span>{icon}</span>{name}{name==='智能工作台'&&<i>NEW</i>}</button>)}</>}
export default function App(){const[items,setItems]=useState<Conversation[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null)
const refresh=()=>listConversations().then(setItems);useEffect(()=>{refresh()},[]);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages])
async function newTask(){const item=await createConversation();setCurrent(item);setMessages([]);await refresh()}
async function openTask(id:string){const item=await getConversation(id);setCurrent(item);setMessages(item.messages||[])}
async function submit(e:FormEvent){e.preventDefault();const content=input.trim();if(!content||busy)return;let task=current;if(!task){task=await createConversation();setCurrent(task)}setInput('');setBusy(true);const user:Message={id:crypto.randomUUID(),role:'user',content,sources:'',created_at:new Date().toISOString()},assistant:Message={id:crypto.randomUUID(),role:'assistant',content:'',sources:'',created_at:new Date().toISOString()};setMessages(old=>[...old,user,assistant]);try{await streamMessage(task.id,content,token=>setMessages(old=>old.map(m=>m.id===assistant.id?{...m,content:m.content+token}:m)));await refresh()}catch(error){setMessages(old=>old.map(m=>m.id===assistant.id?{...m,content:`任务失败：${error instanceof Error?error.message:'未知错误'}`}:m))}finally{setBusy(false)}}
const quick=(text:string)=>{setInput(text);document.querySelector<HTMLTextAreaElement>('.composer textarea')?.focus()};return <div className="shell"><aside className="global-nav"><div className="brand"><b>A</b><div>ATLAS<small>智能体平台</small></div></div><nav><NavGroup label="使用智能体" items={primary}/><NavGroup label="构建智能体" items={build}/><NavGroup label="资源中心" items={resources}/><NavGroup label="平台管理" items={manage}/></nav><footer><strong><i/>本地服务运行中</strong><small>React + FastAPI</small></footer></aside><main><header><div><small>默认工作空间</small><strong>智能工作台</strong></div><div className="top-actions"><button>⌕ 搜索功能或智能体　⌘ K</button><span>♢</span><b>X</b></div></header><div className="workspace"><aside className="task-list"><label><input placeholder="搜索任务"/><span>⌕</span></label><button className="new" onClick={newTask}>□＋　新建任务</button><button>◷　定时任务</button><h4>远程终端 <span>⚙</span></h4><h4>最近任务</h4>{items.map(item=><button className={current?.id===item.id?'selected':''} key={item.id} onClick={()=>openTask(item.id)}><em>{item.title}</em><small>{new Date(item.updated_at).toLocaleDateString()}</small></button>)}</aside><section className="stage"><div className="stage-head"><div><button>◫</button><button onClick={newTask}>□＋</button><strong>{current?.title||'新任务'}</strong></div><button>◌</button></div><div className="conversation">{messages.length===0?<div className="welcome"><div className="agent-mark">A</div><h1>描述需求，开启智能工作方式</h1><p>一站式智能工作台，连接企业知识库与技能工具，替你从规划到执行完成每一项任务。</p></div>:messages.map(m=><div className={`message ${m.role}`} key={m.id}><div>{m.content||<span className="typing">正在思考</span>}</div></div>)}<div ref={end}/></div><div className="dock"><div className="quick"><button onClick={()=>quick('帮我处理并总结一份文档')}>▣ 文档处理</button><button onClick={()=>quick('分析这份业务数据并给出结论')}>⌁ 数据分析</button><button onClick={()=>quick('围绕这个主题进行深度研究')}>⌕ 深度研究</button><button onClick={()=>quick('帮我创建一个业务应用')}>▤ 创建应用</button></div><form className="composer" onSubmit={submit}><textarea rows={2} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder="支持上传图片或文件进行提问，输入 @ 唤起 Skills / 工具 / 知识库"/><div><span>＋　<b>◩ gpt-4.1-mini⌄</b>　♧ Skills　↗ 连接器　◇ 工具　▤ 知识库</span><button disabled={busy||!input.trim()}>↑</button></div></form><small>AI 生成仅供参考，请遵守服务条款和隐私政策</small></div></section></div></main></div>}
